apiVersion: v1
kind: Service
metadata:
    name: counter-cluster-ip-service
spec:
    type: ClusterIP
    selector:
        component: counter
    ports:
        - port: 3070
          targetPort: 3070
