sudo: required
services:
    - docker
env:
    global:
        - SHA=$(git rev-parse HEAD)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
    - docker build -t 1after/api-java-test -f ./api/Dockerfile.test ./api    
script:
    - docker run -e CI=true 1after/api-java-test mvn test    
after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin    
jobs:
    include:
        - stage: build and stage docker images
          if: branch = master
          script: 
            - bash ./build-images.sh
            - bash ./stage-images.sh
        - stage: test docker image
          if: branch = master
          script:
            - bash ./test-images.sh
        - stage: deploy to aws
          if: branch = aws
          script:
            - bash deploy-to-aws.sh
        