sudo: required
services:
    - docker
env:
    global:
        - SHA=$(git rev-parse HEAD)    ß
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin        
deploy:
    provider: script
    script: bash ./deploy.sh        
    on:
        branch: master