apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-java-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: api-java
    template:
        metadata:
            labels:
                component: api-java
        spec:
            containers:
                - name: api-java
                  image: 1after/api-java
                  ports:
                    - containerPort: 8080
                  env:
                    - name: MYSQL_HOST
                      value: mysql-cluster-ip-service
                    - name:  MYSQL_DATABASE
                      value: api
                    - name: MYSQL_USER
                      value: safir
                    - name: REDIS_HOST
                      value: redis-cluster-ip-service
                    - name: REDIS_HOST
                      value: '6379'
                    - name: COUNTER_HOST
                      value: counter-cluster-ip-service
                    - name: COUNTER_PORT
                      value: '3070'
                    - name: MYSQL_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: mysql-vault
                            key: mysqlpassword                  