apiVersion: apps/v1
kind: Deployment
metadata:
    name: counter-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: counter
    template:
        metadata:
            labels:
                component: counter
        spec:
            containers:
                - name: counter
                  image: 1after/counter
                  ports:
                    - containerPort: 3070
                  env:
                    - name: REDIS_HOST
                      value: redis-cluster-ip-service
                    - name: REDIS_PORT
                      value: '6379'                    